language: cpp
compiler: gcc
before_install:
        - sudo apt-get update -qq
        - sudo apt-get install -qq cmake qt5-default libqt5svg5-dev

before_script:
        - mkdir build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=Release ..

script: make

#email:
#- devs@host.org
#on_success: change
#on_failure: always
