site_name: OpenBR
repo_url: https://github.com/biometrics/openbr
site_favicon: docs/img/openbr.ico
copyright: 2012 The MITRE Corporation

theme: spacelab
theme_dir: themes/spacelab/

pages:
- [index.md, Home]
- [install.md, Install]
- [tutorials.md, Tutorials]
- [technical.md, Technical Overviews]
- [contribute.md, More, Contribute]
- [papers.md, More, Publications]
- [docs/c_api.md, API Docs, C API]
- [docs/cpp_api.md, API Docs, C++ Plugin API]
- [docs/cl_api.md, API Docs, Command Line API]
- [docs/plugins/classification.md, Plugin Docs, Classification]
- [docs/plugins/cluster.md, Plugin Docs, Cluster]
- [docs/plugins/core.md, Plugin Docs, Core]
- [docs/plugins/distance.md, Plugin Docs, Distance]
- [docs/plugins/format.md, Plugin Docs, Format]
- [docs/plugins/gallery.md, Plugin Docs, Gallery]
- [docs/plugins/gui.md, Plugin Docs, GUI]
- [docs/plugins/imgproc.md, Plugin Docs, Image Processing]
- [docs/plugins/io.md, Plugin Docs, I/O]
- [docs/plugins/metadata.md, Plugin Docs, Metadata]
- [docs/plugins/output.md, Plugin Docs, Output]
- [docs/plugins/video.md, Plugin Docs, Video]
