site_name: OpenBR
pages:
- [index.md, Home]
- [install.md, Install]
- [tutorials.md, Tutorials]
- [technical.md, Technical Overview]
- [abstractions.md, Docs, Abstractions]
- [plugins.md, Docs, Plugins]
theme: flatly
